/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SelectApartmentImport } from './routes/select-apartment'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as RoommateIndexImport } from './routes/roommate/index'
import { Route as RoommateTasksImport } from './routes/roommate/tasks'
import { Route as RoommateShoppingImport } from './routes/roommate/shopping'
import { Route as RoommateBalancesImport } from './routes/roommate/balances'
import { Route as RoommateLayoutImport } from './routes/roommate/_layout'
import { Route as OnboardingSelectRoleImport } from './routes/onboarding/select-role'
import { Route as OnboardingInviteImport } from './routes/onboarding/invite'
import { Route as OnboardingCreateProfileImport } from './routes/onboarding/create-profile'
import { Route as OnboardingCreateApartmentImport } from './routes/onboarding/create-apartment'
import { Route as OnboardingLayoutImport } from './routes/onboarding/_layout'
import { Route as LandloardSettingsImport } from './routes/landloard/settings'
import { Route as LandloardIncidentsImport } from './routes/landloard/incidents'
import { Route as LandloardApartmentDetailsImport } from './routes/landloard/apartment-details'
import { Route as LandloardLayoutImport } from './routes/landloard/_layout'
import { Route as RoommatePaymentsIndexImport } from './routes/roommate/payments/index'
import { Route as RoommateIncidentsIndexImport } from './routes/roommate/incidents/index'
import { Route as RoommatePaymentsCreateExpenseImport } from './routes/roommate/payments/create-expense'
import { Route as RoommateIncidentsIncidentIdImport } from './routes/roommate/incidents/$incidentId'
import { Route as RoommatePaymentsSettleUpIndexImport } from './routes/roommate/payments/settle-up/index'
import { Route as RoommatePaymentsExpensesIndexImport } from './routes/roommate/payments/expenses/index'
import { Route as RoommatePaymentsSettleUpSuccessImport } from './routes/roommate/payments/settle-up/success'
import { Route as RoommatePaymentsSettleUpDebtIdImport } from './routes/roommate/payments/settle-up/$debtId'
import { Route as RoommatePaymentsExpensesExpenseIdImport } from './routes/roommate/payments/expenses/$expenseId'
import { Route as RoommatePaymentsSettleUpUserToUserIdImport } from './routes/roommate/payments/settle-up/user/$toUserId'

// Create Virtual Routes

const RoommateImport = createFileRoute('/roommate')()
const OnboardingImport = createFileRoute('/onboarding')()
const LandloardImport = createFileRoute('/landloard')()

// Create/Update Routes

const RoommateRoute = RoommateImport.update({
  id: '/roommate',
  path: '/roommate',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const LandloardRoute = LandloardImport.update({
  id: '/landloard',
  path: '/landloard',
  getParentRoute: () => rootRoute,
} as any)

const SelectApartmentRoute = SelectApartmentImport.update({
  id: '/select-apartment',
  path: '/select-apartment',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoommateIndexRoute = RoommateIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommateTasksRoute = RoommateTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommateShoppingRoute = RoommateShoppingImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommateBalancesRoute = RoommateBalancesImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommateLayoutRoute = RoommateLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => RoommateRoute,
} as any)

const OnboardingSelectRoleRoute = OnboardingSelectRoleImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingInviteRoute = OnboardingInviteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingCreateProfileRoute = OnboardingCreateProfileImport.update({
  id: '/create-profile',
  path: '/create-profile',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingCreateApartmentRoute = OnboardingCreateApartmentImport.update({
  id: '/create-apartment',
  path: '/create-apartment',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingLayoutRoute = OnboardingLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => OnboardingRoute,
} as any)

const LandloardSettingsRoute = LandloardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LandloardRoute,
} as any)

const LandloardIncidentsRoute = LandloardIncidentsImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => LandloardRoute,
} as any)

const LandloardApartmentDetailsRoute = LandloardApartmentDetailsImport.update({
  id: '/apartment-details',
  path: '/apartment-details',
  getParentRoute: () => LandloardRoute,
} as any)

const LandloardLayoutRoute = LandloardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LandloardRoute,
} as any)

const RoommatePaymentsIndexRoute = RoommatePaymentsIndexImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommateIncidentsIndexRoute = RoommateIncidentsIndexImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => RoommateRoute,
} as any)

const RoommatePaymentsCreateExpenseRoute =
  RoommatePaymentsCreateExpenseImport.update({
    id: '/payments/create-expense',
    path: '/payments/create-expense',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommateIncidentsIncidentIdRoute =
  RoommateIncidentsIncidentIdImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsSettleUpIndexRoute =
  RoommatePaymentsSettleUpIndexImport.update({
    id: '/payments/settle-up/',
    path: '/payments/settle-up/',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsExpensesIndexRoute =
  RoommatePaymentsExpensesIndexImport.update({
    id: '/payments/expenses/',
    path: '/payments/expenses/',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsSettleUpSuccessRoute =
  RoommatePaymentsSettleUpSuccessImport.update({
    id: '/payments/settle-up/success',
    path: '/payments/settle-up/success',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsSettleUpDebtIdRoute =
  RoommatePaymentsSettleUpDebtIdImport.update({
    id: '/payments/settle-up/$debtId',
    path: '/payments/settle-up/$debtId',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsExpensesExpenseIdRoute =
  RoommatePaymentsExpensesExpenseIdImport.update({
    id: '/payments/expenses/$expenseId',
    path: '/payments/expenses/$expenseId',
    getParentRoute: () => RoommateRoute,
  } as any)

const RoommatePaymentsSettleUpUserToUserIdRoute =
  RoommatePaymentsSettleUpUserToUserIdImport.update({
    id: '/payments/settle-up/user/$toUserId',
    path: '/payments/settle-up/user/$toUserId',
    getParentRoute: () => RoommateRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/select-apartment': {
      id: '/select-apartment'
      path: '/select-apartment'
      fullPath: '/select-apartment'
      preLoaderRoute: typeof SelectApartmentImport
      parentRoute: typeof rootRoute
    }
    '/landloard': {
      id: '/landloard'
      path: '/landloard'
      fullPath: '/landloard'
      preLoaderRoute: typeof LandloardImport
      parentRoute: typeof rootRoute
    }
    '/landloard/_layout': {
      id: '/landloard/_layout'
      path: '/landloard'
      fullPath: '/landloard'
      preLoaderRoute: typeof LandloardLayoutImport
      parentRoute: typeof LandloardRoute
    }
    '/landloard/apartment-details': {
      id: '/landloard/apartment-details'
      path: '/apartment-details'
      fullPath: '/landloard/apartment-details'
      preLoaderRoute: typeof LandloardApartmentDetailsImport
      parentRoute: typeof LandloardImport
    }
    '/landloard/incidents': {
      id: '/landloard/incidents'
      path: '/incidents'
      fullPath: '/landloard/incidents'
      preLoaderRoute: typeof LandloardIncidentsImport
      parentRoute: typeof LandloardImport
    }
    '/landloard/settings': {
      id: '/landloard/settings'
      path: '/settings'
      fullPath: '/landloard/settings'
      preLoaderRoute: typeof LandloardSettingsImport
      parentRoute: typeof LandloardImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/_layout': {
      id: '/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/create-apartment': {
      id: '/onboarding/create-apartment'
      path: '/create-apartment'
      fullPath: '/onboarding/create-apartment'
      preLoaderRoute: typeof OnboardingCreateApartmentImport
      parentRoute: typeof OnboardingImport
    }
    '/onboarding/create-profile': {
      id: '/onboarding/create-profile'
      path: '/create-profile'
      fullPath: '/onboarding/create-profile'
      preLoaderRoute: typeof OnboardingCreateProfileImport
      parentRoute: typeof OnboardingImport
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteImport
      parentRoute: typeof OnboardingImport
    }
    '/onboarding/select-role': {
      id: '/onboarding/select-role'
      path: '/select-role'
      fullPath: '/onboarding/select-role'
      preLoaderRoute: typeof OnboardingSelectRoleImport
      parentRoute: typeof OnboardingImport
    }
    '/roommate': {
      id: '/roommate'
      path: '/roommate'
      fullPath: '/roommate'
      preLoaderRoute: typeof RoommateImport
      parentRoute: typeof rootRoute
    }
    '/roommate/_layout': {
      id: '/roommate/_layout'
      path: '/roommate'
      fullPath: '/roommate'
      preLoaderRoute: typeof RoommateLayoutImport
      parentRoute: typeof RoommateRoute
    }
    '/roommate/balances': {
      id: '/roommate/balances'
      path: '/balances'
      fullPath: '/roommate/balances'
      preLoaderRoute: typeof RoommateBalancesImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/shopping': {
      id: '/roommate/shopping'
      path: '/shopping'
      fullPath: '/roommate/shopping'
      preLoaderRoute: typeof RoommateShoppingImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/tasks': {
      id: '/roommate/tasks'
      path: '/tasks'
      fullPath: '/roommate/tasks'
      preLoaderRoute: typeof RoommateTasksImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/': {
      id: '/roommate/'
      path: '/'
      fullPath: '/roommate/'
      preLoaderRoute: typeof RoommateIndexImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/incidents/$incidentId': {
      id: '/roommate/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/roommate/incidents/$incidentId'
      preLoaderRoute: typeof RoommateIncidentsIncidentIdImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/create-expense': {
      id: '/roommate/payments/create-expense'
      path: '/payments/create-expense'
      fullPath: '/roommate/payments/create-expense'
      preLoaderRoute: typeof RoommatePaymentsCreateExpenseImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/incidents/': {
      id: '/roommate/incidents/'
      path: '/incidents'
      fullPath: '/roommate/incidents'
      preLoaderRoute: typeof RoommateIncidentsIndexImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/': {
      id: '/roommate/payments/'
      path: '/payments'
      fullPath: '/roommate/payments'
      preLoaderRoute: typeof RoommatePaymentsIndexImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/expenses/$expenseId': {
      id: '/roommate/payments/expenses/$expenseId'
      path: '/payments/expenses/$expenseId'
      fullPath: '/roommate/payments/expenses/$expenseId'
      preLoaderRoute: typeof RoommatePaymentsExpensesExpenseIdImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/settle-up/$debtId': {
      id: '/roommate/payments/settle-up/$debtId'
      path: '/payments/settle-up/$debtId'
      fullPath: '/roommate/payments/settle-up/$debtId'
      preLoaderRoute: typeof RoommatePaymentsSettleUpDebtIdImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/settle-up/success': {
      id: '/roommate/payments/settle-up/success'
      path: '/payments/settle-up/success'
      fullPath: '/roommate/payments/settle-up/success'
      preLoaderRoute: typeof RoommatePaymentsSettleUpSuccessImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/expenses/': {
      id: '/roommate/payments/expenses/'
      path: '/payments/expenses'
      fullPath: '/roommate/payments/expenses'
      preLoaderRoute: typeof RoommatePaymentsExpensesIndexImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/settle-up/': {
      id: '/roommate/payments/settle-up/'
      path: '/payments/settle-up'
      fullPath: '/roommate/payments/settle-up'
      preLoaderRoute: typeof RoommatePaymentsSettleUpIndexImport
      parentRoute: typeof RoommateImport
    }
    '/roommate/payments/settle-up/user/$toUserId': {
      id: '/roommate/payments/settle-up/user/$toUserId'
      path: '/payments/settle-up/user/$toUserId'
      fullPath: '/roommate/payments/settle-up/user/$toUserId'
      preLoaderRoute: typeof RoommatePaymentsSettleUpUserToUserIdImport
      parentRoute: typeof RoommateImport
    }
  }
}

// Create and export the route tree

interface LandloardRouteChildren {
  LandloardLayoutRoute: typeof LandloardLayoutRoute
  LandloardApartmentDetailsRoute: typeof LandloardApartmentDetailsRoute
  LandloardIncidentsRoute: typeof LandloardIncidentsRoute
  LandloardSettingsRoute: typeof LandloardSettingsRoute
}

const LandloardRouteChildren: LandloardRouteChildren = {
  LandloardLayoutRoute: LandloardLayoutRoute,
  LandloardApartmentDetailsRoute: LandloardApartmentDetailsRoute,
  LandloardIncidentsRoute: LandloardIncidentsRoute,
  LandloardSettingsRoute: LandloardSettingsRoute,
}

const LandloardRouteWithChildren = LandloardRoute._addFileChildren(
  LandloardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingLayoutRoute: typeof OnboardingLayoutRoute
  OnboardingCreateApartmentRoute: typeof OnboardingCreateApartmentRoute
  OnboardingCreateProfileRoute: typeof OnboardingCreateProfileRoute
  OnboardingInviteRoute: typeof OnboardingInviteRoute
  OnboardingSelectRoleRoute: typeof OnboardingSelectRoleRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingLayoutRoute: OnboardingLayoutRoute,
  OnboardingCreateApartmentRoute: OnboardingCreateApartmentRoute,
  OnboardingCreateProfileRoute: OnboardingCreateProfileRoute,
  OnboardingInviteRoute: OnboardingInviteRoute,
  OnboardingSelectRoleRoute: OnboardingSelectRoleRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface RoommateRouteChildren {
  RoommateLayoutRoute: typeof RoommateLayoutRoute
  RoommateBalancesRoute: typeof RoommateBalancesRoute
  RoommateShoppingRoute: typeof RoommateShoppingRoute
  RoommateTasksRoute: typeof RoommateTasksRoute
  RoommateIndexRoute: typeof RoommateIndexRoute
  RoommateIncidentsIncidentIdRoute: typeof RoommateIncidentsIncidentIdRoute
  RoommatePaymentsCreateExpenseRoute: typeof RoommatePaymentsCreateExpenseRoute
  RoommateIncidentsIndexRoute: typeof RoommateIncidentsIndexRoute
  RoommatePaymentsIndexRoute: typeof RoommatePaymentsIndexRoute
  RoommatePaymentsExpensesExpenseIdRoute: typeof RoommatePaymentsExpensesExpenseIdRoute
  RoommatePaymentsSettleUpDebtIdRoute: typeof RoommatePaymentsSettleUpDebtIdRoute
  RoommatePaymentsSettleUpSuccessRoute: typeof RoommatePaymentsSettleUpSuccessRoute
  RoommatePaymentsExpensesIndexRoute: typeof RoommatePaymentsExpensesIndexRoute
  RoommatePaymentsSettleUpIndexRoute: typeof RoommatePaymentsSettleUpIndexRoute
  RoommatePaymentsSettleUpUserToUserIdRoute: typeof RoommatePaymentsSettleUpUserToUserIdRoute
}

const RoommateRouteChildren: RoommateRouteChildren = {
  RoommateLayoutRoute: RoommateLayoutRoute,
  RoommateBalancesRoute: RoommateBalancesRoute,
  RoommateShoppingRoute: RoommateShoppingRoute,
  RoommateTasksRoute: RoommateTasksRoute,
  RoommateIndexRoute: RoommateIndexRoute,
  RoommateIncidentsIncidentIdRoute: RoommateIncidentsIncidentIdRoute,
  RoommatePaymentsCreateExpenseRoute: RoommatePaymentsCreateExpenseRoute,
  RoommateIncidentsIndexRoute: RoommateIncidentsIndexRoute,
  RoommatePaymentsIndexRoute: RoommatePaymentsIndexRoute,
  RoommatePaymentsExpensesExpenseIdRoute:
    RoommatePaymentsExpensesExpenseIdRoute,
  RoommatePaymentsSettleUpDebtIdRoute: RoommatePaymentsSettleUpDebtIdRoute,
  RoommatePaymentsSettleUpSuccessRoute: RoommatePaymentsSettleUpSuccessRoute,
  RoommatePaymentsExpensesIndexRoute: RoommatePaymentsExpensesIndexRoute,
  RoommatePaymentsSettleUpIndexRoute: RoommatePaymentsSettleUpIndexRoute,
  RoommatePaymentsSettleUpUserToUserIdRoute:
    RoommatePaymentsSettleUpUserToUserIdRoute,
}

const RoommateRouteWithChildren = RoommateRoute._addFileChildren(
  RoommateRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-apartment': typeof SelectApartmentRoute
  '/landloard': typeof LandloardLayoutRoute
  '/landloard/apartment-details': typeof LandloardApartmentDetailsRoute
  '/landloard/incidents': typeof LandloardIncidentsRoute
  '/landloard/settings': typeof LandloardSettingsRoute
  '/onboarding': typeof OnboardingLayoutRoute
  '/onboarding/create-apartment': typeof OnboardingCreateApartmentRoute
  '/onboarding/create-profile': typeof OnboardingCreateProfileRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/roommate': typeof RoommateLayoutRoute
  '/roommate/balances': typeof RoommateBalancesRoute
  '/roommate/shopping': typeof RoommateShoppingRoute
  '/roommate/tasks': typeof RoommateTasksRoute
  '/roommate/': typeof RoommateIndexRoute
  '/roommate/incidents/$incidentId': typeof RoommateIncidentsIncidentIdRoute
  '/roommate/payments/create-expense': typeof RoommatePaymentsCreateExpenseRoute
  '/roommate/incidents': typeof RoommateIncidentsIndexRoute
  '/roommate/payments': typeof RoommatePaymentsIndexRoute
  '/roommate/payments/expenses/$expenseId': typeof RoommatePaymentsExpensesExpenseIdRoute
  '/roommate/payments/settle-up/$debtId': typeof RoommatePaymentsSettleUpDebtIdRoute
  '/roommate/payments/settle-up/success': typeof RoommatePaymentsSettleUpSuccessRoute
  '/roommate/payments/expenses': typeof RoommatePaymentsExpensesIndexRoute
  '/roommate/payments/settle-up': typeof RoommatePaymentsSettleUpIndexRoute
  '/roommate/payments/settle-up/user/$toUserId': typeof RoommatePaymentsSettleUpUserToUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-apartment': typeof SelectApartmentRoute
  '/landloard': typeof LandloardLayoutRoute
  '/landloard/apartment-details': typeof LandloardApartmentDetailsRoute
  '/landloard/incidents': typeof LandloardIncidentsRoute
  '/landloard/settings': typeof LandloardSettingsRoute
  '/onboarding': typeof OnboardingLayoutRoute
  '/onboarding/create-apartment': typeof OnboardingCreateApartmentRoute
  '/onboarding/create-profile': typeof OnboardingCreateProfileRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/roommate': typeof RoommateIndexRoute
  '/roommate/balances': typeof RoommateBalancesRoute
  '/roommate/shopping': typeof RoommateShoppingRoute
  '/roommate/tasks': typeof RoommateTasksRoute
  '/roommate/incidents/$incidentId': typeof RoommateIncidentsIncidentIdRoute
  '/roommate/payments/create-expense': typeof RoommatePaymentsCreateExpenseRoute
  '/roommate/incidents': typeof RoommateIncidentsIndexRoute
  '/roommate/payments': typeof RoommatePaymentsIndexRoute
  '/roommate/payments/expenses/$expenseId': typeof RoommatePaymentsExpensesExpenseIdRoute
  '/roommate/payments/settle-up/$debtId': typeof RoommatePaymentsSettleUpDebtIdRoute
  '/roommate/payments/settle-up/success': typeof RoommatePaymentsSettleUpSuccessRoute
  '/roommate/payments/expenses': typeof RoommatePaymentsExpensesIndexRoute
  '/roommate/payments/settle-up': typeof RoommatePaymentsSettleUpIndexRoute
  '/roommate/payments/settle-up/user/$toUserId': typeof RoommatePaymentsSettleUpUserToUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-apartment': typeof SelectApartmentRoute
  '/landloard': typeof LandloardRouteWithChildren
  '/landloard/_layout': typeof LandloardLayoutRoute
  '/landloard/apartment-details': typeof LandloardApartmentDetailsRoute
  '/landloard/incidents': typeof LandloardIncidentsRoute
  '/landloard/settings': typeof LandloardSettingsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/_layout': typeof OnboardingLayoutRoute
  '/onboarding/create-apartment': typeof OnboardingCreateApartmentRoute
  '/onboarding/create-profile': typeof OnboardingCreateProfileRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/onboarding/select-role': typeof OnboardingSelectRoleRoute
  '/roommate': typeof RoommateRouteWithChildren
  '/roommate/_layout': typeof RoommateLayoutRoute
  '/roommate/balances': typeof RoommateBalancesRoute
  '/roommate/shopping': typeof RoommateShoppingRoute
  '/roommate/tasks': typeof RoommateTasksRoute
  '/roommate/': typeof RoommateIndexRoute
  '/roommate/incidents/$incidentId': typeof RoommateIncidentsIncidentIdRoute
  '/roommate/payments/create-expense': typeof RoommatePaymentsCreateExpenseRoute
  '/roommate/incidents/': typeof RoommateIncidentsIndexRoute
  '/roommate/payments/': typeof RoommatePaymentsIndexRoute
  '/roommate/payments/expenses/$expenseId': typeof RoommatePaymentsExpensesExpenseIdRoute
  '/roommate/payments/settle-up/$debtId': typeof RoommatePaymentsSettleUpDebtIdRoute
  '/roommate/payments/settle-up/success': typeof RoommatePaymentsSettleUpSuccessRoute
  '/roommate/payments/expenses/': typeof RoommatePaymentsExpensesIndexRoute
  '/roommate/payments/settle-up/': typeof RoommatePaymentsSettleUpIndexRoute
  '/roommate/payments/settle-up/user/$toUserId': typeof RoommatePaymentsSettleUpUserToUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | '/'
  | '/login'
  | '/select-apartment'
  | '/landloard'
  | '/landloard/apartment-details'
  | '/landloard/incidents'
  | '/landloard/settings'
  | '/onboarding'
  | '/onboarding/create-apartment'
  | '/onboarding/create-profile'
  | '/onboarding/invite'
  | '/onboarding/select-role'
  | '/roommate'
  | '/roommate/balances'
  | '/roommate/shopping'
  | '/roommate/tasks'
  | '/roommate/'
  | '/roommate/incidents/$incidentId'
  | '/roommate/payments/create-expense'
  | '/roommate/incidents'
  | '/roommate/payments'
  | '/roommate/payments/expenses/$expenseId'
  | '/roommate/payments/settle-up/$debtId'
  | '/roommate/payments/settle-up/success'
  | '/roommate/payments/expenses'
  | '/roommate/payments/settle-up'
  | '/roommate/payments/settle-up/user/$toUserId'
  fileRoutesByTo: FileRoutesByTo
  to:
  | '/'
  | '/login'
  | '/select-apartment'
  | '/landloard'
  | '/landloard/apartment-details'
  | '/landloard/incidents'
  | '/landloard/settings'
  | '/onboarding'
  | '/onboarding/create-apartment'
  | '/onboarding/create-profile'
  | '/onboarding/invite'
  | '/onboarding/select-role'
  | '/roommate'
  | '/roommate/balances'
  | '/roommate/shopping'
  | '/roommate/tasks'
  | '/roommate/incidents/$incidentId'
  | '/roommate/payments/create-expense'
  | '/roommate/incidents'
  | '/roommate/payments'
  | '/roommate/payments/expenses/$expenseId'
  | '/roommate/payments/settle-up/$debtId'
  | '/roommate/payments/settle-up/success'
  | '/roommate/payments/expenses'
  | '/roommate/payments/settle-up'
  | '/roommate/payments/settle-up/user/$toUserId'
  id:
  | '__root__'
  | '/'
  | '/login'
  | '/select-apartment'
  | '/landloard'
  | '/landloard/_layout'
  | '/landloard/apartment-details'
  | '/landloard/incidents'
  | '/landloard/settings'
  | '/onboarding'
  | '/onboarding/_layout'
  | '/onboarding/create-apartment'
  | '/onboarding/create-profile'
  | '/onboarding/invite'
  | '/onboarding/select-role'
  | '/roommate'
  | '/roommate/_layout'
  | '/roommate/balances'
  | '/roommate/shopping'
  | '/roommate/tasks'
  | '/roommate/'
  | '/roommate/incidents/$incidentId'
  | '/roommate/payments/create-expense'
  | '/roommate/incidents/'
  | '/roommate/payments/'
  | '/roommate/payments/expenses/$expenseId'
  | '/roommate/payments/settle-up/$debtId'
  | '/roommate/payments/settle-up/success'
  | '/roommate/payments/expenses/'
  | '/roommate/payments/settle-up/'
  | '/roommate/payments/settle-up/user/$toUserId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelectApartmentRoute: typeof SelectApartmentRoute
  LandloardRoute: typeof LandloardRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RoommateRoute: typeof RoommateRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelectApartmentRoute: SelectApartmentRoute,
  LandloardRoute: LandloardRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  RoommateRoute: RoommateRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/select-apartment",
        "/landloard",
        "/onboarding",
        "/roommate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/select-apartment": {
      "filePath": "select-apartment.tsx"
    },
    "/landloard": {
      "filePath": "landloard",
      "children": [
        "/landloard/_layout",
        "/landloard/apartment-details",
        "/landloard/incidents",
        "/landloard/settings"
      ]
    },
    "/landloard/_layout": {
      "filePath": "landloard/_layout.tsx",
      "parent": "/landloard"
    },
    "/landloard/apartment-details": {
      "filePath": "landloard/apartment-details.tsx",
      "parent": "/landloard"
    },
    "/landloard/incidents": {
      "filePath": "landloard/incidents.tsx",
      "parent": "/landloard"
    },
    "/landloard/settings": {
      "filePath": "landloard/settings.tsx",
      "parent": "/landloard"
    },
    "/onboarding": {
      "filePath": "onboarding",
      "children": [
        "/onboarding/_layout",
        "/onboarding/create-apartment",
        "/onboarding/create-profile",
        "/onboarding/invite",
        "/onboarding/select-role"
      ]
    },
    "/onboarding/_layout": {
      "filePath": "onboarding/_layout.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/create-apartment": {
      "filePath": "onboarding/create-apartment.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/create-profile": {
      "filePath": "onboarding/create-profile.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/invite": {
      "filePath": "onboarding/invite.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/select-role": {
      "filePath": "onboarding/select-role.tsx",
      "parent": "/onboarding"
    },
    "/roommate": {
      "filePath": "roommate",
      "children": [
        "/roommate/_layout",
        "/roommate/balances",
        "/roommate/shopping",
        "/roommate/tasks",
        "/roommate/",
        "/roommate/incidents/$incidentId",
        "/roommate/payments/create-expense",
        "/roommate/incidents/",
        "/roommate/payments/",
        "/roommate/payments/expenses/$expenseId",
        "/roommate/payments/settle-up/$debtId",
        "/roommate/payments/settle-up/success",
        "/roommate/payments/expenses/",
        "/roommate/payments/settle-up/",
        "/roommate/payments/settle-up/user/$toUserId"
      ]
    },
    "/roommate/_layout": {
      "filePath": "roommate/_layout.tsx",
      "parent": "/roommate"
    },
    "/roommate/balances": {
      "filePath": "roommate/balances.tsx",
      "parent": "/roommate"
    },
    "/roommate/shopping": {
      "filePath": "roommate/shopping.tsx",
      "parent": "/roommate"
    },
    "/roommate/tasks": {
      "filePath": "roommate/tasks.tsx",
      "parent": "/roommate"
    },
    "/roommate/": {
      "filePath": "roommate/index.tsx",
      "parent": "/roommate"
    },
    "/roommate/incidents/$incidentId": {
      "filePath": "roommate/incidents/$incidentId.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/create-expense": {
      "filePath": "roommate/payments/create-expense.tsx",
      "parent": "/roommate"
    },
    "/roommate/incidents/": {
      "filePath": "roommate/incidents/index.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/": {
      "filePath": "roommate/payments/index.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/expenses/$expenseId": {
      "filePath": "roommate/payments/expenses/$expenseId.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/settle-up/$debtId": {
      "filePath": "roommate/payments/settle-up/$debtId.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/settle-up/success": {
      "filePath": "roommate/payments/settle-up/success.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/expenses/": {
      "filePath": "roommate/payments/expenses/index.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/settle-up/": {
      "filePath": "roommate/payments/settle-up/index.tsx",
      "parent": "/roommate"
    },
    "/roommate/payments/settle-up/user/$toUserId": {
      "filePath": "roommate/payments/settle-up/user/$toUserId.tsx",
      "parent": "/roommate"
    }
  }
}
ROUTE_MANIFEST_END */
