name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ lint, build ]

    steps:
      # 1. Check out your PR branch (full history)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Fetch all remote branches so origin/<base> exists
      - name: Fetch all branches
        run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'

      # 3. Install Node.js & cache
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 4. Install deps
      - name: Install dependencies
        run: npm ci

      # 5. Run lint or build depending on the matrix target
      - name: Run ${{ matrix.target }}
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          npx nx affected \
            --target=${{ matrix.target }} \
            --parallel \
            --base=origin/${BASE} \
            --head=${{ github.sha }}
