name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # make sure the PR’s target branch exists locally
      - name: Fetch base branch
        run: |
          git fetch origin \
            ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Lint affected
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          npx nx affected --target=lint \
            --parallel \
            --base=origin/${BASE} \
            --head=${{ github.sha }}

      - name: Build affected
        run: |
          BASE=${{ github.event.pull_request.base.ref }}
          npx nx affected --target=build \
            --parallel \
            --base=origin/${BASE} \
            --head=${{ github.sha }}
